"use client";

import { useMemo } from "react";

import { ConnectionDot } from "@/components/ConnectionDot";
import { useFlash } from "@/hooks/useFlash";
import { fmtCurrency, fmtPercent, fmtSignedCurrency, signClass, signGlyph } from "@/lib/format";
import { computeLivePortfolio } from "@/lib/portfolio";
import { useTerminal } from "@/state/terminal";

/** One label-over-value block in the header rail. */
function Stat({
  label,
  value,
  valueClass = "text-ink",
  flashClass = "",
  flashKey = 0,
  size = "md",
}: {
  label: string;
  value: string;
  valueClass?: string;
  flashClass?: string;
  flashKey?: number;
  size?: "md" | "lg";
}) {
  return (
    <div className="flex flex-col gap-0.5 px-4">
      <span className="text-[9px] font-semibold uppercase tracking-[0.16em] text-muted">
        {label}
      </span>
      <span
        key={flashKey}
        className={`numeric ${size === "lg" ? "text-xl" : "text-sm"} leading-none ${valueClass} ${flashClass} rounded-sm`}
      >
        {value}
      </span>
    </div>
  );
}

export function Header() {
  const { portfolio, prices, status, health } = useTerminal();
  const live = useMemo(() => computeLivePortfolio(portfolio, prices), [portfolio, prices]);

  // Round before flashing: sub-cent drift would strobe the header continuously.
  const flash = useFlash(portfolio ? Math.round(live.totalValue * 100) : null);

  return (
    <header className="flex h-14 shrink-0 items-center justify-between border-b border-border bg-panel px-4">
      <div className="flex items-center gap-3">
        <div className="flex h-7 w-7 items-center justify-center rounded-sm bg-accent text-sm font-black text-terminal">
          F
        </div>
        <div className="leading-none">
          <div className="text-sm font-bold tracking-[0.2em] text-ink">FINALLY</div>
          <div className="mt-0.5 text-[9px] uppercase tracking-[0.18em] text-muted">
            AI Trading Workstation
          </div>
        </div>
      </div>

      <div className="flex items-center divide-x divide-border">
        <Stat
          label="Portfolio Value"
          value={portfolio ? fmtCurrency(live.totalValue) : "—"}
          size="lg"
          valueClass="text-accent font-semibold"
          flashClass={flash.className}
          flashKey={flash.flashKey}
        />
        <Stat label="Cash" value={portfolio ? fmtCurrency(live.cashBalance) : "—"} />
        <Stat
          label="Unrealized P&L"
          value={
            portfolio
              ? `${signGlyph(live.totalUnrealizedPnl)} ${fmtSignedCurrency(live.totalUnrealizedPnl)}`
              : "—"
          }
          valueClass={signClass(live.totalUnrealizedPnl)}
        />
        <Stat
          label="Return"
          value={portfolio ? fmtPercent(live.totalUnrealizedPnlPercent) : "—"}
          valueClass={signClass(live.totalUnrealizedPnlPercent)}
        />
        <div className="flex items-center gap-4 pl-4">
          {health ? (
            <span
              className="rounded-sm border border-border-strong px-2 py-0.5 text-[9px] font-semibold uppercase tracking-[0.14em] text-muted"
              title={
                health.market_source === "simulator"
                  ? "Prices are generated by the built-in simulator"
                  : "Prices are polled from the Massive API"
              }
            >
              {health.market_source}
              {health.llm_mock ? " · mock ai" : ""}
            </span>
          ) : null}
          <ConnectionDot status={status} />
        </div>
      </div>
    </header>
  );
}
